name: Build Exercise Service
on: 
  push: 
    branches: [main]
jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.filter.outputs.changes }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        github-server-url: http://10.200.162.14:9008

    - uses: dorny/paths-filte@v2
      id: filter
      with:
        base: ${{ gitea.ref }}
        filters: |
          wall:
            - wall/**
          user:
            - user/**
            - basic/**'
            - pom.xml
          gateway:
            - gateway/**
            - basic/**'
            - pom.xml                  


  build:

    needs: pre-build
    strategy:
      matrix:
        service: ${{ fromJSON(needs.pre-build.outputs.service) }}
    runs-on: ubuntu-latest

    steps:

    - name: echo
      run: |
        echo "构建${{ matrix.service }}"
        echo "${{ needs.pre-build.outputs.service }}"
        echo "${{ fromJSON(needs.pre-build.outputs.service) }}"        

    